name: Build RPMs
on:
  push:
    branches: [ master, ovirt-4.4 ]
  pull_request:
env:
  EXPORT_DIR: exported-artifacts
jobs:
  rpm:
    runs-on: ubuntu-latest
    name: rpm-${{ matrix.distro }}
    container: quay.io/ovirt/buildcontainer:${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: centos-stream-9
            tag: el9stream
          - distro: centos-stream-10
            tag: el10stream
    steps:
    - uses: ovirt/checkout-action@main
    - name: Install dependencies
      run: dnf -y install createrepo_c git make python3-devel rpm-build systemd
    - name: Build RPMs
      run: ./automation/rpm.sh
    - uses: ovirt/upload-rpms-action@main
      with:
        directory: ${{ env.EXPORT_DIR }}
