name: CI
on:
  push:
    branches:
      - master
      - ovirt-4.4
  pull_request:
env:
  EXPORT_DIR: exported-artifacts
jobs:
  rpm:
    runs-on: ubuntu-latest
    name: rpm-${{ matrix.distro }}
    container: quay.io/centos/centos:${{ matrix.tag }}
    strategy:
      matrix:
        include:
          - distro: el8stream
            tag: stream8
          - distro: el9stream
            tag: stream9
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dnf -y install createrepo_c git make python3-devel rpm-build systemd
    - name: Build RPMs
      run: ./automation/rpm.sh
    - uses: ovirt/upload-rpms-action@v2
      with:
        directory: ${{ env.EXPORT_DIR }}
